baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'PRN ?'
theme = 'archie'

[params]
	mode="dark" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = ".....Pro Rants for Nurses by nurses"



[services]
  [services.disqus]
    shortname = '@roamingstatus'


# Social Tags

[[params.social]]
name = "Facebook"
icon = "facebook"
url = "https://www.facebook.com/profile.php?id=61561547853992"

#[[params.social]]
#name = "Twitter"
#icon = "twitter"
#url = "https://twitter.com/"



[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3
